// Definitions are code, not records. sourceKey binds only to our legacy adapters.
const define = (
  id,
  name,
  type,
  unit,
  category,
  aggregation,
  route,
  description,
  extra = {},
) =>
  Object.freeze({
    id,
    sourceKey: id,
    name,
    type,
    unit,
    category,
    aggregation,
    target: null,
    active: true,
    primary: true,
    route,
    description,
    ...extra,
  });
export const TRACKERS = Object.freeze([
  define(
    "sleep.duration",
    "睡眠时长",
    "duration",
    "min",
    "健康",
    "latest",
    "sleep",
    "按醒来日期记录的睡眠分钟，已扣除夜间清醒时间。",
  ),
  define(
    "body.weight",
    "体重",
    "number",
    "kg",
    "健康",
    "latest",
    "fitness",
    "身体测量中的体重；没有测量时间的同日记录无法确认先后。",
  ),
  define(
    "workout.minutes",
    "运动时长",
    "duration",
    "min",
    "健康",
    "sum",
    "fitness",
    "训练记录的实际分钟，不含每周计划的预计时间。",
  ),
  define(
    "study.minutes",
    "专业课学习时长",
    "duration",
    "min",
    "学习",
    "sum",
    "courses",
    "仅汇总专业课复习记录，不叠加 Focus 或英语时长。",
  ),
  define(
    "english.minutes",
    "英语学习时长",
    "duration",
    "min",
    "学习",
    "sum",
    "english",
    "仅包含剧集观看与阅读中已填写的分钟；单词记录没有时长。",
  ),
  define(
    "guitar.minutes",
    "吉他练习时长",
    "duration",
    "min",
    "生活",
    "sum",
    "guitar",
    "练琴记录的分钟；曲目、BPM 和录音保留在原页面。",
  ),
  define(
    "income.amount",
    "公众号收入",
    "money",
    "CNY",
    "收入",
    "sum",
    "income",
    "已录账号收入合计，存储单位为分；不含销售成交，不代表所有账号已填齐。",
  ),
  define(
    "emotion.intensity",
    "情绪强度",
    "score",
    "强度",
    "生活",
    "latest",
    "emotion",
    "原始强度 1–5，并非心情好坏评分；不同状态的强度不能解释为同一种情绪。",
    { min: 1, max: 5 },
  ),
  ...[
    ["height", "身高"],
    ["waist", "腰围"],
    ["arm", "臂围"],
    ["shoulder", "肩宽"],
  ].map(([key, name]) =>
    define(
      "body." + key,
      name,
      "number",
      "cm",
      "健康",
      "latest",
      "fitness",
      "来自身体测量；同日无时间记录以稳定 ID 排序展示，不推断实际先后。",
      { primary: false },
    ),
  ),
]);
export function getTracker(id) {
  const definition = TRACKERS.find((t) => t.id === id);
  if (!definition) throw new Error("未知指标：" + id);
  return definition;
}
